apiVersion: v1
kind: Pod
metadata:
  name: pdpod
spec:
  containers:
    - name: c1
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: pdmount
          mountPath: /cache
  volumes:
    - name: pdmount
      gcePersistentDisk:
        pdName: mydisk
        fsType: ext4
