apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: deployblugreenstrategy
spec:
 replicas: 3
 selector:
  matchLabels:
   env: dev
 template:
  metadata:
   name: deployblugreenstrategypods
   labels:
    env: dev
  spec:
   containers:
    - name: deployblugreenstrategycons
      image: nginx
      ports:
       - containerPort: 80
       
---

apiVersion: v1
kind: Service
metadata:
 name: nopoforblugreendeploy
spec:
 type: NodePort
 selector:
  env: dev
 ports:
  - name: nopoforblugreendeploy
    port: 80
    targetPort: 80
    nodePort: 30002
