apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: firstdeployment
spec:
 replicas: 4
 selector:
  matchLabels:
   app: web
 template:
  metadata:
   name: deploynginxpod
   labels:
    app: web
  spec:
   containers:
    - name: deploynginxcon
      image: nginx
      ports:
       - containerPort: 80
       
---

apiVersion: v1
kind: Service
metadata:
 name: nopofordeploymnet
spec:
 type: NodePort
 selector:
  app: web
 ports:
  - name: nopofordeploymnet
    port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP
