apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: deployrecreatestrategy
spec:
 replicas: 3
 selector:
  matchLabels:
   env: dev
 strategy:
  type: Recreate
 template:
  metadata:
   name: deployrecreatestrategypods
   labels:
    env: dev
  spec:
   containers:
    - name: deployrecreatestrategycons
      image: ranjithsaccount/ranjith:myfirstimage
      ports:
       - containerPort: 80
       
---

apiVersion: v1
kind: Service
metadata:
 name: nopoforrecreatedeploy
spec:
 type: NodePort
 selector:
  env: dev
 ports:
  - name: nopoforrecreatedeploy
    port: 80
    targetPort: 80
    nodePort: 30003
