apiVersion: v1
kind: Pod
metadata:
        name: noquota
spec:
        containers:
                - name: noquota
                  image: nginx
                  ports:
                          - containerPort: 80
