apiVersion: v1
kind: Pod
metadata:
        name: besteffort
        namespace: resourcequota
spec:
        containers:
                - name: besteffort
                  image: nginx
                  ports:
                          - containerPort: 80
