apiVersion: v1
kind: Pod
metadata:
        name: rprobehttp
spec:
        containers:
                - name: rprobehttp
                  image: nginx
                  ports:
                          - containerPort: 80
                  readinessProbe:
                          httpGet:
                                  path: /index.html
                                  port: 8080
                          initialDelaySeconds: 10
                          periodSeconds: 1
