apiVersion: v1
kind: Pod
metadata:
 name: configmapfrmfile
spec:
 containers:
  - name: configmapfrmfilecon
    image: mysql
    ports:
     - containerPort: 3300
    env:
     - name: MYSQL_ROOT_PASSWORD
       valueFrom:
        configMapKeyRef:
         name: confmapfile
         key: sqlpass
