apiVersion: v1
kind: Pod
metadata:
 name: configmaplitenvs
spec:
 containers:
  - name: configmaplitenvscon
    image: mysql
    ports:
     - containerPort: 3300
    envFrom:
     - configMapRef:
        name: confmaplitenvs
