apiVersion: v1
kind: Pod
metadata:
 name: dockerregistrysecret
spec:
 containers:
  - name: dockerregistrysecretcon
    image: ranjithsaccount/ranjith:myfirstimage
    ports:
     - containerPort: 80
    imagePullPolicy: Always
 imagePullSecrets:
  - name: dockerhub

