apiVersion: v1
kind: Pod
metadata:
 name: mysqlgenericsecret
spec:
 containers:
  - name: mysqlgenericsecret
    image: mysql
    ports:
     - containerPort: 3306
    env:
     - name: MYSQL_ROOT_PASSWORD
       valueFrom:
        secretKeyRef:
         name: secpasswd
         key: mysqlpassword
